### ISSUE TITLE
Test rig blueprint is not openable in 0.15.18

### ISSUE THREAD

**Issue by Baughn** [justarandomgeek/factorio-conman#2]
All I get if I paste it is "Failed to import string: Unknown version ('H')"...

**Comment by justarandomgeek** [comment]
It's an old style blueprint string. I'll try to get a new one in there tonight, but in the mean time you should be able to run it through any of the many 0.14 to 0.15 blueprint converters!

**Comment by Baughn** [comment]
Thanks! I didn't realize there *were* blueprint strings before.

For anyone else who comes across this, one such converter: https://factoriolayouts.com/blueprint/convert
