### ISSUE TITLE
Any chance of adding a way to get feedback from conman if construction/deconstruction is complete?

### ISSUE THREAD

**Issue by xGnoSiSx** [justarandomgeek/factorio-conman#3]
Hi,

I've made a similar request under Recursive blueprints as well. We need an elegant way of knowing when a command is finished on the circuit signal.

>There was recursive blueprints extended out of 0.16
>
>Can you consider adding that functionality? The deployer would check the area in the commands at a configurable interval (say every 2-3 seconds) and report 2 signals to the circuit network:
>
>   ghost signal "G" = number of items that are still ghosts.
>    deconstruct signal "D" = number of items marked for deconstruction.
>
>you capture, x,y,w,h only once on command trigger and you hold and report previous G,D (even zeros)

https://mods.factorio.com/mod/recursive-blueprints/discussion/5d44628bde13a8000c99f418

Thank you.

**Comment by justarandomgeek** [comment]
Watch your roboports for all construction bots being available again. There's no good api for monitoring ghosts like that, and doing it "the hard way" would utterly destroy UPS in an already very expensive mod. (And the game doesn't track it in any helpful way, so a request for an API probably isn't happening either.)

**Comment by xGnoSiSx** [comment]
Roboports won't cut it. If you don't have the materials robots won't launch, so you need to track material as well, so the logic becomes horrendrous in size. What other options are there?
