### ISSUE TITLE
item requests on constant combinator

### ISSUE THREAD

**Issue by ichvii** [justarandomgeek/factorio-conman#4]
In your current master version here, the ConstructionOrder for a constant combinator with one or more item signals adds item requests to the entity.

I assume that is not intended behaviour.

Adding ["constant-combinator"]=nocc2  at the end of ConstructionOrderEntitySpecific in line 246 should fix this.

**Comment by justarandomgeek** [comment]
Thanks, I'm surprised my testsuite didn't catch this one! I've added the appropriate test for it as well.
