### ISSUE TITLE
support for books?

### ISSUE THREAD

**Issue by ichvii** [justarandomgeek/factorio-conman#5]
Do you plan on ever adding support for blueprint books?

I build a very simple mod based on conman, that allows to add a blueprint to a specific position in a book or get a copy of a blueprint in a specific position in the book. The mod renames everything to be compatible with conman. 

The main idea is to include a book on both sides of the recipe. 

[hithere_0.17.0.zip](https://github.com/justarandomgeek/factorio-conman/files/3838636/hithere_0.17.0.zip)

I included the file if you are interested. If you dont plan on adding support for books, ill upload this with less unnecessary code to the modding portal.

**Comment by justarandomgeek** [comment]
I haven't considered books at all in a while, but they do seem like the next obvious thing after editing. Unfortunately, renaming everything means that looking at a diff will be pretty worthless :/ Can you quickly describe your ideal command set extension for operating on/with books? I've got a few (conflicting) ideas of how they should work, and i'm not sure which is best!

**Comment by ichvii** [comment]
Id say if blueprint-book signal is not zero, you do any command that interacts with a blueprint instead with the blueprint stored at that position in the book. If you want to capture a blueprint above the length of the book, you add that many blueprints before.

Because of the library deleting multiple blueprints, it would be nice to have one operation, that renames all blueprints by adding their number to the name. If you cannot assign a name to an empty blueprint, you place eg one tile of concrete in that blueprint to assign a name.

Furthermore, blueprint-book=-1 transfers the book to output inventory.

You might also want to add a method to acquire an empty book or blueprint, as the game does not allow you to craft them and grants them freely. And one to delete them. These signals would just be blueprint == -? and blueprint-book == -? .

The changes in the recipe file are easy to see and i replaced the on tick manager function with my stuff. Apart from that, i only added the functions EjectBlueprintBook, DeleteBlueprintBook and DeleteBlueprint, which are self explanatory.

Edit: I only added a "2" in the item, entity and recipe names, all functions are called the same.

**Comment by justarandomgeek** [comment]
0.17.4 has a crapload of new book/blueprint commands, which I think should satisfy all your needs! :)
