### ISSUE TITLE
Readposition for x,y,u or v =0

### ISSUE THREAD

**Issue by ichvii** [justarandomgeek/factorio-conman#8]
The function Readposition leads to a crash, if x,y,u or v is zero and the offset for that does not exist.

local function ReadPosition(signals,secondary,offset)
  if not secondary then
    local p = get_signals_filtered(signalsets.position1,signals)
    if offset then
      p.x = (p.x or 0)+offset.x
      p.y = (p.y or 0)+offset.y
    end
    return p
  else
    local p = get_signals_filtered(signalsets.position2,signals)
    if offset then
      p.x = (p.x or 0)+offset.x
      p.y = (p.y or 0)+offset.y
    end
    return p
  end
end

It would be improved as:

local function ReadPosition(signals,secondary,offset)
  offset=offset or {x=0,y=0}
  if not secondary then
    local p = get_signals_filtered(signalsets.position1,signals)
    p.x = (p.x or 0)+offset.x
    p.y = (p.y or 0)+offset.y
    return p
  else
    local p = get_signals_filtered(signalsets.position2,signals)
    p.x = (p.x or 0)+offset.x
    p.y = (p.y or 0)+offset.y
    return p
  end
end

This should fix the crash. 

I dont know how to update my fork and create a pull request with this. This specifically caused a crash when using the construction order in a blueprint at coordinates 0,0. I am fairly certain, this is the cause of the crash. If the value of signal-X is zero and offset is nil, it will not correct p.x to 0 instead of nil.

**Comment by justarandomgeek** [comment]
fixed in 0.18.3
